import { Cinzel, Inter, Murecho, Zen_Kurenaido } from 'next/font/google'
import '../styles/globals.css'
import SupabaseProvider from './supabase-provider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const ZenKurenaido = Zen_Kurenaido({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

const cinzel = Cinzel({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cinzel',
})

// const murecho = Murecho({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-inter',
// })

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='jp'
      className={`${cinzel.variable} ${ZenKurenaido.className} h-screen w-screen bg-sakura-pattern bg-repeat`}
    >
      <body>
        <SupabaseProvider>{children}</SupabaseProvider>
      </body>
    </html>
  )
}
